export const bn = {
  book: {
    title: [
      "Pather Panchali",
      "Aparajito",
      "Chokher Bali",
      "Ghare Baire",
      "Shesher Kobita",
      "Char Adhyay",
      "Debi",
      "Palli Samaj",
      "Devdas",
      "Srikanta",
      "Parineeta",
      "Durgeshnandini",
      "Kapalkundala",
      "Anandamath",
      "Krishnakanter Will",
      "Rajmohan's Wife",
      "Padma Nadir Majhi",
      "Putul Nacher Itikatha",
      "Chhinna Patra",
      "Bishabriksha",
      "Sei Somoy",
      "Prothom Alo",
      "Aranyer Din Ratri",
      "Kalbela",
      "Uttoradhikar",
      "Kalpurush",
      "Shatabdir Kanya",
      "Kachher Manush",
      "Dahan",
      "Balika Badhu",
      "Na Hanyate",
      "Antarjali Yatra",
      "Herbert",
      "Ei Shahar Theke Ekhon",
      "Mouchak",
      "Tenida Samagra",
      "Feluda Samagra",
      "Professor Shonku Samagra",
      "Kakababu Samagra",
      "Gogoler Kirti",
      "Gitanjali",
      "Sonar Tori",
      "Banalata Sen",
      "Rupasi Bangla",
      "Shreshtho Kobita",
      "Bhul Korechi Bhul",
      "Bidrohi",
      "Dolonchampa",
      "Bishad Sindhu",
      "Shrestho Kobita",
      "Megh o Roudro",
      "Bonolota",
      "Atmaprakash",
      "Shahaj Path",
      "Se Ar Se",
      "Poka Makorer Gaan",
      "Lajja",
      "Rudali",
      "Anya Jiban",
      "Rater Kolkata",
      "Ekattorer Dinguli",
      "Ekhono Somoy",
      "Krittibash",
      "Chotoder Rabindranath",
      "Dwitiyo Adhyay",
      "Bipodshankha",
      "Chaturanga",
      "Datta",
      "Shuvashini",
      "Khelar Sathi",
      "Krittibasi Ramayan",
      "Dramatic Moments",
      "Bhadate Jachchhi",
      "Golpo 101",
      "Swapner Bazar",
      "Aandhar Nayak",
      "Jokhon Brishti Naamlo",
      "Rajarshi",
      "Ashani Sanket",
      "Kshudhita Pashan",
      "Kari o Komal",
      "Kalantarer Kabita",
    ],
    author: [
      "Rabindranath Tagore",
      "Sarat Chandra Chattopadhyay",
      "Bankim Chandra Chattopadhyay",
      "Bibhutibhushan Bandyopadhyay",
      "Manik Bandopadhyay",
      "Ishwar Chandra Vidyasagar",
      "Michael Madhusudan Dutt",
      "Dinabandhu Mitra",
      "Jagadish Gupta",
      "Mir Mosharraf Hossain",
      "Sunil Gangopadhyay",
      "Samaresh Majumdar",
      "Samaresh Basu",
      "Suchitra Bhattacharya",
      "Shirshendu Mukhopadhyay",
      "Leela Majumdar",
      "Narayan Gangopadhyay",
      "Nabarun Bhattacharya",
      "Joy Goswami",
      "Shankha Ghosh",
      "Jibanananda Das",
      "Shakti Chattopadhyay",
      "Kazi Nazrul Islam",
      "Subhash Mukhopadhyay",
      "Binoy Majumdar",
      "Satyajit Ray",
      "Premendra Mitra",
      "Adrish Bardhan",
      "Khagendranath Mitra",
      "Tarashankar Bandyopadhyay",
      "Satinath Bhaduri",
      "Maitreyi Devi",
      "Buddhadeb Guha",
      "Kamalkumar Majumdar",
      "Syed Mujtaba Ali",
      "Abul Bashar",
      "Mahasweta Devi",
      "Humayun Ahmed",
      "Selina Hossain",
      "Hasan Azizul Huq",
      "Begum Rokeya",
      "Zahir Raihan",
      "Anisul Hoque",
      "Rokeya Sakhawat Hossain",
      "Al Mahmud",
      "Shamsur Rahman",
      "Abu Ishaque",
    ],
    publisher: [
      "Boighar",
      "University Press Limited",
      "Nabajug",
      "Sheba Prokashoni",
      "Sheba Prokashoni",
      "Gangchil",
      "Ananda Publishers",
      "Abhijan Publishers",
      "Oitijjhya",
      "Gangchil",
      "Gangchil",
      "Dey's Publishing",
      "Boighar",
      "Sahitya Samsad",
      "Khan Brothers",
      "Sahitya Samsad",
      "Mowla Brothers",
      "Patra Bharati",
      "Mowla Brothers",
      "Dey's Publishing",
      "Abhijan Publishers",
      "Mitralaya",
      "Patra Bharati",
      "Mowla Brothers",
      "Chhaya Prakashani",
      "Sheba Prokashoni",
      "Nabajug",
      "Abhijan Publishers",
      "Agamee Prakashani",
      "Gangchil",
    ],
  },
};
